### ISSUE TITLE
Secondary Certificate Authentication in HTTP/2

### ISSUE THREAD

**Issue by dimaqq** [python-hyper/h2#1223]
May be of interest, new HTTP/2 frames are introduced:
https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs-06#section-3

Current status: Mozilla considers it worthy of considering, or something like that.

**Comment by Kriechi** [comment]
The mentioned internet draft is now expired and archived - so I'll close it here as well. Thanks for raising it though!
