### ISSUE TITLE
Use allowlist_externals when next version of tox is released

### ISSUE THREAD

**Issue by annevk** [python-hyper/h2#1227]
As a follow-up to https://github.com/python-hyper/hyper-h2/issues/1207, https://github.com/tox-dev/tox/issues/1491 is now fixed.

**Comment by sethmlarson** [comment]
Thank you! If you could provide a PR it'd be a quick review :)

**Comment by annevk** [comment]
I can change the tox file, but I'm not sure how to require a particular version of tox.
