### ISSUE TITLE
Proposal: Rename this repository to "h2"

### ISSUE THREAD

**Issue by sethmlarson** [python-hyper/h2#1245]
The name has [caused confusion](https://github.com/encode/httpx/discussions/1477) due to the `hyper` project being deprecated. And to be fair I've definitely forgotten that this URL is special and doesn't match it's PyPI package name. Should we rename the project to simply `h2`?

**Comment by pgjones** [comment]
I think this is sensible.

**Comment by Kriechi** [comment]
I agree - I considered it before v4 release, but didn't have a strong reason yet.

**Comment by sethmlarson** [comment]
Since there's 3 in favor I'll leave this open a few days to see if any are opposed, if not I'll go ahead with the rename.

**Comment by florimondmanca** [comment]
Thanks for picking up that conversation from the HTTPX repo. :)

I would personally also support a rename of the repo, especially given that the PyPI name and package name are already `h2`.

**Comment by sethmlarson** [comment]
I've got time to work on OSS today and seems there's many +1s now, going forward with the rename.
