### ISSUE TITLE
No forum or discussion area

### ISSUE THREAD

**Issue by tridentsx** [python-hyper/h2#1249]
I have a problem 5G Core telco environment its common to have http2 without prior knowledge and with and without TLS, its not clear to me how to setup this from a client using h2, Sorry I know this is my competence problem but I couldn't find any other place to ask for help on this.

The prior knowledge part referrs to the alpn section but not use any references to alpn, and its not helpful.

**Comment by pgjones** [comment]
You can join us on [gitter](https://gitter.im/python-hyper/community)
