### ISSUE TITLE
Incorrect dependency in conda build for h2 version 3.2.0

### ISSUE THREAD

**Issue by Richiecakes** [python-hyper/h2#1255]
(Sorry if this is the wrong place to raise this - if so please kindly point me to who maintains the conda builds)

I noticed in [this](https://libraries.io/conda/h2/3.2.0) conda build, the dependency for hyperframe is wrong.

It is currently `>=5.1.0`, but it should be `>=5.2.0` , as it is correctly stated in the setup.py of this project.

Otherwise we get the error `AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL'`

**Comment by Kriechi** [comment]
Yes, this is the wrong place to raise this. I do not know who maintains this conda build, but there is a "Something wrong with this page? Make a suggestion" link in the bottom right corner...
