### ISSUE TITLE
[Question] How can I send a POST request?

### ISSUE THREAD

**Issue by MT-Cash** [python-hyper/h2#1260]
I'm trying to communicate with the Apple Push Notification service (APN) which uses HTTP/2 ([docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1)).

I've (sucessfully) used [hyper](https://pypi.org/project/hyper/) before for that with code that roughly looks like this:

```python
from hyper import HTTPConnection
import json

bearer_token = "foo"
device_token = "bar"
payload = {}

request_headers = {
    "apns-expiration": "0",
    "apns-priority": "10",
    "authorization": f"bearer {bearer_token}",
}

conn = HTTPConnection("api.development.push.apple.com:443")
conn.request(
    "POST", f"/3/device/{device_token}",
    json.dumps(payload).encode(),
    headers=request_headers
)
resp = conn.get_response()
print(resp.status)
print(resp.reason)
print(resp.read())
```

How would an equivalent with h2 look like?

**Comment by Kriechi** [comment]
h2 itself is just a bare-bones sans-io library. Meaning, you need to handle your own I/O operations and understand the HTTP/2 protocol to make sense of the emitted events from h2. A good starting point is also the first code snippet in our main README file and our HTTP client examples: https://python-hyper.org/projects/hyper-h2/en/stable/examples.html#example-clients

If you want a fully-fledged HTTP library to send requests and read responses, I suggest https://www.python-httpx.org/ (which we also recommend as `hyper` replacement)

**Comment by MT-Cash** [comment]
I wanted to use httpx, but it didn't work:

* https://stackoverflow.com/q/69084783/562769
* https://github.com/encode/httpx/discussions/1841 - there are some new pointers I haven't seen before; I'll try that
